### ISSUE TITLE
submitPost returns temp PostHashHex

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/deso-workspace#1]
When submitting a post with post.submitPost it returns the first PostHashHex, but this is a temp value. The confirmed (real) PostHashHex can be found after the transaction is signed in TxnHashHex or in the PostEntryResponse.PostHashHex. The issue is that these values are not returned.

Might be good to add an obj TnxRes (to all calls?) or something to have both responses. Not sure what the best way is.

**Comment by DeSoDog** [comment]
yeah I've been thinking on this too. I'll run my solution by you once I come up with something!

**Comment by mvanhalen** [comment]
Added #16 for this
