### ISSUE TITLE
Add support for server-side usage

### ISSUE THREAD

**Issue by freeman-jiang** [deso-protocol/deso-workspace#11]
- Reduce reliance on browser-specific elements like `localStorage` and iframes unless absolutely necessary (eg. for identity)
- For instance: calls to `getUsersStateless` should be done without needing a browser
- Remove browser reliance in the `Deso` object constructor

**Comment by carlosgnet** [comment]
Absolutely!

**Comment by ankushKun** [comment]
+1, Unable to use `getPostsStateless` in react-native because there is no localStorage.

**Comment by ankushKun** [comment]
I was able to find a solution for using deso-protocol in NextJS using react `useEffect` and `useState`

```js
import { useState, useEffect } from "react";
import { Deso } from 'deso-protocol';

export default function Home() {
    const [deso, setDeso] = useState(null);

    useEffect(() => {
        const deso = new Deso();
        setDeso(deso);
    }, []);

    if (deso) {
        var posts = deso.posts.getPostsStateless({});
        posts.then(function(result) {
            console.log(result);
        });
    }

    return (jsx here)
}
```

![image](https://user-images.githubusercontent.com/50258860/169786252-89ba32e3-cb66-4824-aaea-067b9a49fda4.png)

This article explains what's happening
https://developer.school/snippets/react/localstorage-is-not-defined-nextjs

cc: @AdityaChaudhary0005

**Comment by DeSoDog** [comment]
0.4.0 added server support. Only changes needed are updating the constructor like so const deso = new Deso({ identityConfig: { host: "server" } });

Additionally you can find an express server template if you guys want to play around with it 

https://github.com/DeSoDog/Express-App-Starter-Pack
