### ISSUE TITLE
DeSo Creator Coin Bug

### ISSUE THREAD

**Issue by ECOE-Ken** [deso-protocol/deso-workspace#18]
Thread with screenshots on-chain at: https://bitclout.com/posts/7eca6f1e3914314a1085da1d70ce7e76bd723c8c03e72977530cc2065f941dc3
NOTE:
If this report will apply to receive the bug bounty offered we can use it to get our VR Universe of 3D Worlds back online for the DeSo members & app/node Dev teams to use to onboard new users to DeSo. We have Twitter setup & ready to launch it to non-DeSo web2 users in mass.
~ Ken Stewart
on-chain @ECOE

**Comment by DeSoDog** [comment]
That application does not use the DeSo library
