### ISSUE TITLE
expirationDays field is not working while creating derived keys

### ISSUE THREAD

**Issue by AdityaChaudhary0005** [deso-protocol/deso-workspace#32]
So my payload request is something like this:
```js
 const payload = {
      expirationDays: 365,
      transactionSpendingLimitResponse: {
        GlobalDESOLimit: 1 * 1e9,
        TransactionCountLimitMap: {
          AUTHORIZE_DERIVED_KEY: 2,
          FOLLOW: 1000000,
        },
      },
    };
```
    
I want the derived keys to be valid for one year but identity is only generating keys for 30 days: 
![image](https://user-images.githubusercontent.com/55331140/173027020-2689ff30-d5dc-4d9d-8f47-2ec7fe6b3c20.png)

It looks like the package is ignoring the `expirationDays` key

**Comment by sungkhum** [comment]
Yes, this is super important. I have a use case where I want the key only valid for 1 day. It is really important that we be able to change this.

**Comment by DeSoDog** [comment]
Hey guys, holding off on the update until the next minor release of the library, goal is to get it out today so sit tight.

**Comment by sungkhum** [comment]
Awesome!
