### ISSUE TITLE
Identity iframe window is not centered

### ISSUE THREAD

**Issue by brootle** [deso-protocol/deso-workspace#38]
The Identity iframe window position is fixed to top left corner of the screen instead of being centered. This is actually strange as when I am using DeSo API this window is centered, when I am using DeSo protocol JS library, it's not centered.

You can test it here https://hub.deso.org/#/identity/identity-login

@diamondhands0 @lazynina @DeSoDog

**Comment by DeSoDog** [comment]
Let me know if it works how you want it to / expect it to

**Comment by mvanhalen** [comment]
Ok cool will check it out. @DeSoDog

**Comment by brootle** [comment]
@DeSoDog @mvanhalen can you post code example here on how to use that update? I checked [https://hub.deso.org/#/identity/identity-login](url) but it's still not centered there

**Comment by mvanhalen** [comment]
@DeSoDog if you publish a new version of the npm it will help. I cannot reference the Github folder for some reason in my build process.

**Comment by DeSoDog** [comment]
0.5.1 or greater should include those changes. Note the change doesn't center the window by default, but it does provide the ability to override the height, width, top, and left position.

Below you can see two different arguments the first being access level and the rest handle sizing and positioning of the prompt. 

These values get directly plugged into the window.open call as the "window features" parameter which you can read more about here https://developer.mozilla.org/en-US/docs/Web/API/Window/open.

            await deso.identity.login("4", {
              left: 100,
              top: 100,
              height: 500,
              width: 500,
            });

@mvanhalen @brootle

**Comment by mvanhalen** [comment]
This is live on [nftz.me](nftz.me) now. Works great could finally get rid of some old code. Stuff is getting mature now.
