### ISSUE TITLE
stuck while installing rosetta DeSo

### ISSUE THREAD

**Issue by liyang783** [deso-protocol/deso-workspace#48]
The logs always look like this.
HyperSync: currently syncing prefixes: ([5])

 Remaining prefixes ([[7] [8] [10] [11] [12] [17] [18] [19] [20] [21] [22] [23] [25] [26] [27] [28] [29] [30] [31] [32] [33] [34] [35] [36] [37] [39] [40] [41] [ 43] [44] [45] [46] [47] [48] [49] [50] [51] [52] [53] [54] [55] [56] [57] [58] [59] [60] [61] [62]])

**Comment by ItsAditya-xyz** [comment]
is it about hub.deso.org? looks like this issue belongs to core repo

**Comment by liyang783** [comment]
Start rosetta DeSo via script /rosetta-deso/scripts/mainnet/online.sh

**Comment by DeSoDog** [comment]
Not a library issue
