### ISSUE TITLE
ReactJS isn't able to resolve 'crypto'

### ISSUE THREAD

**Issue by ItsAditya-xyz** [deso-protocol/deso-workspace#49]
![image](https://user-images.githubusercontent.com/55331140/181436566-73606247-d23b-4e04-9a2b-e42bbb455728.png)
Getting this error while using deso-protocol library.
solution is to add resolve.crypt=False in webpack.js in /node_modules/react-scripts folder. But unfortunately I can't edit node_modules in vercel..

**Comment by DeSoDog** [comment]
We rely on some crypto packages that are native to node so we need to let webpack know about them in your webpack config. This should work for ya

https://github.com/DeSoDog/Social-App-Starter-Pack/blob/main/config-overrides.js
