### ISSUE TITLE
can not run with  "deso-protocol": "^0.8.2",

### ISSUE THREAD

**Issue by ropolexi** [deso-protocol/deso-workspace#72]
I'm trying to add deso to react app but can not run with latest version

Error  with "deso-protocol": "^0.8.2"

But works with "deso-protocol": "^0.1.2"

Any idea why?

**Comment by ropolexi** [comment]
This also works "deso-protocol": "^0.3.0"

**Comment by jsonpreet** [comment]
Getting error


```
ERROR in ./node_modules/deso-protocol/src/lib/utils/Utils.js 11:17-34

Module not found: Error: Can't resolve 'crypto' in 'D:\Projects\React\circleit\node_modules\deso-protocol\src\lib\utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
```

**Comment by ropolexi** [comment]
@ItsAditya-xyz @tijno Any feedback on this?

**Comment by tijno** [comment]
not sure

@DeSoDog will know for sure

**Comment by DeSoDog** [comment]
Oh yeah, we added some crypto libraries a while back that require polyfills. Here's an example of the required polyfills in a create react app. https://github.com/DeSoDog/Social-App-Starter-Pack/blob/main/config-overrides.js

**Comment by ropolexi** [comment]
why the official repo is so buggy? Where are the core teams? Please fix this since first thing dev land on your site is the example that does not work.
