### ISSUE TITLE
Issues with Getting client side web token and switching users

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/deso-workspace#74]
Some questions about package usage

1. We have the option to switch account on NFTz (not signout). What would be the preferred way to do this? With deso-protocol library? Like unload the package an iframe?
2. When users are coming back to our sitee and we just initiate the deso-protocol package to login. But often the JWT token has some issues. Calling the function does not return an error, but it´s not working either. Is there some event I need to wait for first? Or can one be added?
3. Is it possible to embed the iframe in html already or is that not recommend and let the package do that?
4. On iOS when signing op our new user the connect function asks to unlock the wallet first. This results in the user need to click connect button twice. Any suggestions on what to do?

I think the (wrong) combination of these cause some issue on NFTz so would like to optimize and know what would be best to do.

**Comment by mvanhalen** [comment]
@lazynina @DeSoDog @jackson-dean Your input please not sure whom is best to ask. Thanks.

**Comment by sungkhum** [comment]
Would be great to see this fixed - causing pretty bad UX issues @lazynina @DeSoDog @jackson-dean

**Comment by mvanhalen** [comment]
@lazynina saw some updates for ready status on iframe. Could that be related to this. See it was reverted? So, it´s being looked into?

**Comment by jackson-dean** [comment]
Just doing some cleanup of old issues. Is this still a thing @mvanhalen @sungkhum ?

**Comment by jackson-dean** [comment]
This used to be an issue with the encryption key stored inside of the iframe local storage. If a user logged out it would invalidate the encryption key and generate a new one which would break generating jwts for any users still logged in. Now that we've migrated to a derived key login flow this should no longer be an issue.
