### ISSUE TITLE
Fix access levels in deso-protocol

### ISSUE THREAD

**Issue by ItsAditya-xyz** [deso-protocol/deso-workspace#79]
When you take level 3 access from deso identity, and perform transactions like UPDATE_PROFILE, DIAMONDS, BASIC_TRANSFER, it is supposed to open an identity popup to confirm the transaction.

But desoJS completely blocks the transaction.
After creating the UPDATE_PROFILE txn when client has given level 3 access, the library doesn't open the identity popup which it should do ideally.

Pls fix this. this is annoying for users who want to use client apps securely without giving level 4 access.

EDIT: you can't test this on localhost bcz there is no identity level login there. all logins made in localhost are level 4 access

cc: @lazynina @DeSoDog

**Comment by jsonpreet** [comment]
@lazynina @DeSoDog any response on this?

**Comment by brootle** [comment]
I decided to retire deso-protocol JS SDK and move to light version that only does user authorization and signing transactions, so there is really no reason to add features for existing JS SDK

**Comment by jsonpreet** [comment]
> I decided to retire deso-protocol JS SDK and move to light version that only does user authorization and signing transactions, so there is really no reason to add features for existing JS SDK

Yes, You are right and always right.

**Comment by jackson-dean** [comment]
This issue should be resolved in the new identity library, though still an issue in the old deso-protocol lib. We will eventually replace the underlying implementaton in deso-protocol with the new library, though not sure the ETA.

**Comment by jackson-dean** [comment]
We have moved the main deso-protocol lib to use the new derived key flow which removes access levels in favor of derived key permissions so this should be a much better experience now.
