### ISSUE TITLE
DeSo identity window stays blank while using identity login

### ISSUE THREAD

**Issue by AdityaChaudhary0005** [deso-protocol/deso-workspace#9]
Here is the issue
![image](https://user-images.githubusercontent.com/55331140/161314214-2e20b9d3-ff2e-4f21-8b2c-3ebbea6cd7d2.png)

I am using reactJS btw.
and code for the component:
```jsx
import React from "react";
import DeSo from "deso-protocol";
export default function Landing() {
  const handleLogin = async () => {
    const deso = new DeSo();
    const request = 3;
    const response = await deso.identity.login(request);
    console.log(response);
  };
  return (
    <>
      <div> A landing page</div>

      <button
        className='button'
        onClick={() => {
          handleLogin();
        }}>
        Login
      </button>
    </>
  );
}
```

**Comment by DeSoDog** [comment]
Interesting, could you share your package json? I just checked the identity login prompt from the deso-react template and it was working as expected. 
https://github.com/DeSoDog/deso-react

**Comment by DeSoDog** [comment]
Actually, I think the issue may be the initializing call in the constructor is async. What happens if you move the constructor call outside  the landing Component? 

If that's the issue I should be able to write up a solution pretty quickly

**Comment by AdityaChaudhary0005** [comment]
Thanks! I re-installed the library and moved the constructor call outside the component and it did work!

**Comment by starykolarz** [comment]
Had similar issue recently with derive. Maybe this will help someone. I did some oldschoold trial and error :-)  Turned out that it was the webview parameter - I tried to be too outspken and included it with 'false'.  Turns out it only works with 'undefined' or not including it at all (which is same thing); passing either true or false makes the derive window blank.
